import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { ThemeProvider } from "./context/theme";
import TopNav from "../components/nav/TopNav";

export const metadata = {
  title: "Next Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body>
          <TopNav />

          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
